### ISSUE TITLE
IANA: "delegated_credential" parameter

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/draft-ietf-tls-subcerts#11]
Section 6: The text seems to register "delegated_credential" (singular), while the IANA
registry shows delegated_credentials (plural).   If the plural form is correct, consider whether updates are needed throughout (i.e., not just the IANA Considerations section).  Please review and update as needed.  

Original: 
   This document registers the "delegated_credential" extension in the
   "TLS ExtensionType Values" registry.  The "delegated_credential"
   extension has been assigned a code point of 34.

See https://www.iana.org/assignments/tls-extensiontype-values/

Note: If the IANA registry needs to be updated, we will request an update before publication.

**Comment by jsalowey** [comment]
@grittygrease @bifurcation I think IANA registry should be updated to "delegated_credential"

**Comment by grittygrease** [comment]
Let's go with "delegated_credential"

**Comment by lbartholomew-rpc** [comment]
The update from "delegated_credentials" to "delegated_credential" has been flagged for update pre-PUB (i.e., just prior to publication, we will email IANA with request to make this update).
