### ISSUE TITLE
delegated credential (DC):  Usage of abbreviation and expansion

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/draft-ietf-tls-subcerts#16]
Sections 1 and subsequent:  We see that the text
alternates between "DC" and "delegated credential" (for example,
Paragraphs 2 through 4 of Section 4.1.2).  Would you like to use
"DC" after its initial expansion in Section 1?

**Comment by grittygrease** [comment]
I would prefer to use "delegated credential" in cases in which the term is not used in a hyphenated form such as "DC-enabled"
