### ISSUE TITLE
Question re. "it" in Section 7.5

### ISSUE THREAD

**Issue by lbartholomew-rpc** [rfc-editor/draft-ietf-tls-subcerts#17]
Section 7.5:  To what does "it" refer in this sentence
- the delegated credentials, the expiry timestamps, or something else?

Original:
 A service could determine the client
 time and clock skew by creating several delegated credentials with
 different expiry timestamps and observing whether the client would
 accept it.

**Comment by jsalowey** [comment]
I believe it refers to the delegated credentials.  @grittygrease @bifurcation maybe the following would be better:
"A service could determine the client
time and clock skew by creating several delegated credentials with
different expiry timestamps and observing which credentials the client accepts"

**Comment by grittygrease** [comment]
I'm happy with Joe's suggestion.
