### ISSUE TITLE
Display for Kazuho Oku's name in Acknowledgements section (XML time)

### ISSUE THREAD

**Issue by lbartholomew-rpc** [rfc-editor/draft-ietf-tls-subcerts#19]
Acknowledgements:  After this document is converted to XML, please let us know if
you would like us to list Kazuho Oku's name per RFCs 9110 and 9218.

**Comment by jsalowey** [comment]
I believe that would be preferred unless @grittygrease or @bifurcation or other authors know otherwise.

**Comment by grittygrease** [comment]
Yes, let's present it as in RFC 9218.
