### ISSUE TITLE
Terms that might be used inconsistently

### ISSUE THREAD

**Issue by lbartholomew-rpc** [rfc-editor/draft-ietf-tls-subcerts#21]
The following terms appear to be used inconsistently
in this document.  Please let us know which form is preferred.

 back-end / Back-End (running text in Section 3.2)
 credential / Credential (e.g., "the credential" and
   "the Credential" in running text)
 front-end / Front-End (running text in Section 3.2)

**Comment by jsalowey** [comment]
My preference would be front-end and back-end in the text.  
I think section 4 should remain The Credential since it refers to the structure.

**Comment by lbartholomew-rpc** [comment]
Two pending items:

1. Missed earlier:  The two instances of "taken into consideration when using Delegated Certificates" need to be changed to either "taken into consideration when using Delegated Credentials" or "taken into consideration when using delegated credentials", depending on the authors' choice of whether or not to consistently initial-capitalize this term. 
2. Related to 1. in that capitalization should be consistent throughout:  We need to find out whether "the credential" or "the Credential" should be used.

**Comment by grittygrease** [comment]
Answers:
1. "Delegated Certificates" should not be used, only "Delegated Credentials" The one use in security considerations should be changed to "Delegated Credentials"
2. Credential should only be capitalized when beginning a sentence or referring specifically to the "Credential" structure. The text seems to do this correctly.
