### ISSUE TITLE
Question re. "CertificateVerify" and "signature algorithm" in IANA Considerations

### ISSUE THREAD

**Issue by lbartholomew-rpc** [rfc-editor/draft-ietf-tls-subcerts#22]
Section 4:  We do not see any mention of           
"CertificateVerify"
or "signature algorithm" in Section 11 ("IANA Considerations") of
RFC 8446.  Please confirm that this citation is correct and will be
clear to readers.

Original:
 Only
 signature algorithms allowed for use in CertificateVerify messages
 are allowed (as described in [RFC8446] Section 11).

**Comment by sginoza** [comment]
@bifurcation @grittygrease, please review and reply regarding this issue, plus the other 8 pending issues.

**Comment by jsalowey** [comment]
@bifurcation @grittygrease It seems this might be better to refer to [RFC8446] section 4.4.3 instead.

**Comment by grittygrease** [comment]
This reference is mistaken. It does not list which signature algorithms can be used in CertificateVerify messages in RFC 8446 Section 11, or in RFC 8446 at all. This line can be removed:

"Only signature algorithms allowed for use in CertificateVerify messages are allowed (as described in {{RFC8446, Section 11}})."
